---
global:
  scrape_interval: "5s"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets:
          - "pushgateway:9091"
  - job_name: "mongo"
    static_configs:
      - targets:
          - "mongo-exporter:9216"
  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://192.168.0.1/rainloop/
          - http://192.168.0.8:8000/
          - https://192.168.0.5:8006/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
  - job_name: "blackbox-icmp"
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
          - prometheus
          - 192.168.0.250
          - 192.168.0.252
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
  - job_name: "node"
    static_configs:
      - targets:
          - "192.168.0.1:9100"
  - job_name: cadvisor
    static_configs:
    - targets:
      - cadvisor:8080  
  - job_name: 'pve'
    static_configs:
      - targets:
        - 192.168.0.5  # Proxmox VE node.
    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: pve-exporter:9221  # PVE exporter.
  - job_name: mysql-monitor
    static_configs:
    - targets:
      - mssql-exporter:4000
       

#Alertmanager settings

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
